### ISSUE TITLE
wrong time label

### ISSUE THREAD

**Issue by MauMaxxa** [suzuki-0000/CountdownLabel#2]
`
    countdownLabel = CountdownLabel(frame: centro, minutes: 60)
    countdownLabel.timeFormat = "hh:ss"
    countdownLabel.textAlignment = .Center
    countdownLabel.font = UIFont.boldSystemFontOfSize(60)
    countdownLabel.animationType = .Evaporate
    countdownLabel.countdownDelegate = self
    print(countdownLabel.text)
`

print shows 00:01:00 (correct), but label in screen starts from 12:00 and ends in one minute, instead of starting at 01:00

What am i doing wrong?

Thanks

**Comment by suzuki-0000** [comment]
this is the bug.. I try to fix it.

**Comment by suzuki-0000** [comment]
is your time format `hh:ss` correct? it may be `mm:ss`

**Comment by suzuki-0000** [comment]
please re-open if any problems remain
