### ISSUE TITLE
Xcode 10.1 and Swift 4.2

### ISSUE THREAD

**Issue by shoaibnomani** [suzuki-0000/CountdownLabel#43]
Please include support for xcode 10 and swift 4.2. I'm getting a lot of errors.

**Comment by allstar456** [comment]
in the pods, selected CountdownLabel targets, then in the "Build Settings" -> "Swift Compiler Language" , chose Swift 4.2(defualt 4.0)

**Comment by shoaibnomani** [comment]
> in the pods, selected CountdownLabel targets, then in the "Build Settings" -> "Swift Compiler Language" , chose Swift 4.2(defualt 4.0)

Thank you. The issue got resolved.
