### ISSUE TITLE
No such module "CountdownLabel" with CocoaPods

### ISSUE THREAD

**Issue by PedroAnibarro1** [suzuki-0000/CountdownLabel#6]
Hi,

     Xcode throws me 'No such module "CountdownLabel"' when installing with cocoa pods. Any idea?

**Comment by suzuki-0000** [comment]
I push new tag 1.1.2, can you try it?

**Comment by PedroAnibarro1** [comment]
I did a pod update but still, when I do a clean it appears the same message. I have to go to Edit Schemes, Build, Added and put it on top of the list, clean again and then Xcode recognizes it.

**Comment by PedroAnibarro1** [comment]
Nvm, I build it and everything is working. Thanks
