### ISSUE TITLE
cannot build in Xcode 14:

### ISSUE THREAD

**Issue by lexuanquynh** [suzuki-0000/CountdownLabel#60]
cannot build in Xcode 14:
<img width="788" alt="Screenshot 2022-07-08 at 12 51 13" src="https://user-images.githubusercontent.com/17588791/177925796-9b6cb7c8-82d3-4dc6-a4cb-cdd2790914ef.png">

**Comment by yogeshrathore123** [comment]
Xcode 15.2 getting error in pod below is screenshot.
<img width="827" alt="Screenshot 2024-02-23 at 7 21 28 PM" src="https://github.com/suzuki-0000/CountdownLabel/assets/16184452/e5e8f33f-f1d8-4dc8-bd76-13ef55e1ac27">
<img width="827" alt="Screenshot 2024-02-23 at 7 21 28 PM" src="https://github.com/suzuki-0000/CountdownLabel/assets/16184452/3cd582cc-a728-4d1f-9458-7a699783e704">

**Comment by lexuanquynh** [comment]
I think you should custom the countdown label by yourself. 
This library is not update.
