### ISSUE TITLE
Error while using Carthage

### ISSUE THREAD

**Issue by PedroAnibarro1** [suzuki-0000/CountdownLabel#7]
Hi,

  I can't get to install your framework using Carthage. Any idea why? 

*** Fetching CountdownLabel
*** Fetching LTMorphingLabel
*** Checking out LTMorphingLabel at "0.2.0"
*** Checking out CountdownLabel at "1.1.1"
*** xcodebuild output can be found in /var/folders/3x/bfw4yk_d5nz_rcd0b4jcj5b80000gn/T/carthage-xcodebuild.cmPGDT.log
*** Building scheme "LTMorphingLabel" in LTMorphingLabelDemo.xcodeproj
*** Building scheme "CountdownLabel" in CountdownLabel.xcodeproj
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/Pello/Library/Developer/Xcode/DerivedData/CountdownLabel-cczgpbazxfezknchetkgpxakippz/Build/Intermediates/CountdownLabel.build/Release-iphoneos/CountdownLabel.build/Script-89B3C64E1C50780100A02978.sh
(1 failure)
ld: warning: directory not found for option '-F/Users/Pello/Google Drive/Geek Solutions/Yes You Can Reminder/Yes You Can Reminder/Carthage/Checkouts/CountdownLabel/Frameworks'
ld: warning: directory not found for option '-F/Users/Pello/Google Drive/Geek Solutions/Yes You Can Reminder/Yes You Can Reminder/Carthage/Checkouts/CountdownLabel/Frameworks'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/Pello/Google Drive/Geek Solutions/Yes You Can Reminder/Yes You Can Reminder/Carthage/Checkouts/CountdownLabel/CountdownLabel.xcodeproj -scheme CountdownLabel -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/Pello/Library/Developer/Xcode/DerivedData/CountdownLabel-cczgpbazxfezknchetkgpxakippz/Build/Intermediates/CountdownLabel.build/Release-iphoneos/CountdownLabel.build/Script-89B3C64E1C50780100A02978.sh
(1 failure)

**Comment by suzuki-0000** [comment]
I pushed  tag1.1.3 and worked property
```
*** Fetching CountdownLabel
*** Fetching LTMorphingLabel
*** Checking out LTMorphingLabel at "0.2.0"
*** Checking out CountdownLabel at "1.1.3"
*** xcodebuild output can be found in /var/folders/nw/w9lkyg4x3v122grh8c0zdhkhqlj6fb/T/carthage-xcodebuild.3GS0Xy.log
*** Building scheme "LTMorphingLabel" in LTMorphingLabelDemo.xcodeproj
*** Building scheme "CountdownLabel" in CountdownLabel.xcodeproj
```

please re-open if something bad
